--- #YAML:1.0
name:                Term-Size-ReadKey
version:             0.01
abstract:            Perl extension for retrieving terminal size (using Term::ReadKey)
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Adriano R. Ferreira <ferreira@cpan.org>
distribution_type:   module
requires:     
    Term::ReadKey:                 0
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
