--- #YAML:1.0
name:                Term-Size-ReadKey
version:             0.02
abstract:            Retrieving terminal size (via Term::ReadKey)
license:             perl
author:              
    - Adriano R. Ferreira <ferreira@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Exporter:                      0
    strict:                        0
    Term::ReadKey:                 0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
